
    create table order_product (
       order_id bigint not null,
        product_id bigint not null,
        primary key (order_id, product_id)
    );

    create table product (
       id bigint generated by default as identity,
        description varchar(255),
        image_uri varchar(255),
        name varchar(255),
        price double,
        primary key (id)
    );

    create table tb_order (
       id bigint generated by default as identity,
        address varchar(255),
        latitude double,
        longitude double,
        moment timestamp,
        status integer,
        primary key (id)
    );

    alter table order_product 
       add constraint FKhnfgqyjx3i80qoymrssls3kno 
       foreign key (product_id) 
       references product;

    alter table order_product 
       add constraint FKc1hr3gkcmqc95fqpu9k97fq60 
       foreign key (order_id) 
       references tb_order;
